### ISSUE TITLE
cloud client keeps crashing after i changed the font

### ISSUE THREAD

**Issue by CashierNub** [CloudClientDev/cloudclient#28] opened 2023-01-17 07:33 UTC

**Comment by jordoncodes** [comment] 2023-01-17 07:34
duplicate of #12?

**Comment by CashierNub** [comment] 2023-01-17 07:37
imma try if deleting the .cloud file works

**Comment by jordoncodes** [comment] 2023-01-17 07:37
yup

**Comment by jordoncodes** [comment] 2023-01-21 14:03
this should be closed

**Closed** 2023-01-22 00:47 UTC
